version: 0.2

phases:
  pre_build:
    commands:
      - echo "starting pre_build phase..."
  build:
    commands:
      - echo "starting build phase..."
      - ./gradlew clean test bootJar
  post_build:
    commands:
      - echo "starting post_build phase and renaming to tweets.jar ..."
      - mv build/libs/*.jar tweets.jar

artifacts:
  files:
    - tweets.jar

reports:
  jacoco-report:
    files:
      - 'build/reports/jacoco/test/jacocoTestReport.xml'
    file-format: 'JACOCOXML'