version: 0.2
phases:
  pre_build:
    commands:
      - echo "on to pre_build phase..."
  build:
    commands:
      - echo "onto build phase..."
      - ./gradlew clean test bootJar
  post_build:
    commands:
      - echo "onto post_build phase..."
artifacts:
  type: zip
  files:
    - 'build/libs/*.jar'